variables:
CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

stages:
- build-entity
- build-webservice
- release-webservice

maven-build:
stage: build-entity
image: maven:latest
script:
    - cd entity
    - mvn deploy -s settings.xml -DskipTests

build-webservice:
stage: build-webservice
image: docker:20.10.16
services:
    - docker:20.10.16-dind
before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
script:
    - cd webservice
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

release-master-webservice:
stage: release-webservice
image: docker:20.10.16
services:
    - docker:20.10.16-dind
before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
script:
    - cd webservice
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
only:
    - main

release-dev-webservice:
stage: release-webservice
script:
    - cd webservice
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_TEST_IMAGE
    - docker push $CONTAINER_TEST_IMAGE
only:
    - dev

